name: DICOMO2014 Mobile
permalink: /:categories/:title/
#markdown: redcarpet
markdown: kramdown
pygments: true
lsi: false
encoding: utf-8
author:
  name: DICOMO2014実行委員会
  email: dicomo2014-inquiry@dicomo.org

site_url: http://dicomo2014.github.io

favorite:
  star: "<font color='orange'>★</font>"
  addmessage: "お気に入りに追加"
  removemessage: "<font color='orange'>★</font>お気に入りを解除"

roommap:
  image: /images/senkei-bw.png
  width: 3516
  height: 3041

# navigation bar settings

navigation:
- text: DICOMO2014 Mobile
  url: /
  icon: home
- text: Program
  url: /program/
  icon: calendar
- text: Sessions
  url: /session/
  icon: bullets
- text: People
  url: /people/
  icon: user
- text: Access
  url: /access/
  icon: location
